- ci/update.sh
- coder-cli-nightly.rb
- coder-cli.rb
and updates to 1.28.2
I will add a job to the monorepo to automatically run this on release
> chore: automate updating formulae

- coder-cli-nightly.rb
- coder-cli.rb
Reverts coder/homebrew-coder#48
> Revert "Release 1.31.2"

- .github/workflows/test.yaml
Fixes build breakage caused by https://github.com/actions/runner-images/issues/6283
> Add brew to path on linux

- README.md
Related to https://github.com/coder/coder/issues/1925#issuecomment-1305013817
> docs(readme): update tap name

- Formula/coder.rb
This automatic PR was triggered by the release of Coder v2.1.5
> coder 2.1.5

- Formula/coder.rb
This automatic PR was triggered by the release of Coder v2.2.0
> coder 2.2.0

- Formula/coder.rb
This automatic PR was triggered by the release of Coder v2.2.1
> coder 2.2.1

- Formula/coder.rb
This automatic PR was triggered by the release of Coder v2.3.0
> coder 2.3.0

- Formula/coder.rb
This automatic PR was triggered by the release of Coder v2.3.1
> coder 2.3.1

- Formula/coder.rb
This automatic PR was triggered by the release of Coder v2.3.2
> coder 2.3.2

- Formula/coder.rb
This automatic PR was triggered by the release of Coder v2.3.3
> coder 2.3.3

- Formula/coder.rb
This automatic PR was triggered by the release of Coder v2.4.0
> coder 2.4.0

- Formula/coder.rb
This automatic PR was triggered by the release of Coder v2.5.0
> coder 2.5.0

- Formula/coder.rb
This automatic PR was triggered by the release of Coder v2.5.1
> coder 2.5.1

- Formula/coder.rb
This automatic PR was triggered by the release of Coder v2.6.0
> coder 2.6.0

- Formula/coder.rb
This automatic PR was triggered by the release of Coder v2.7.0
> coder 2.7.0

- Formula/coder.rb
This automatic PR was triggered by the release of Coder v2.7.1
> coder 2.7.1

- Formula/coder.rb
This automatic PR was triggered by the release of Coder v2.7.2
> coder 2.7.2

- Formula/coder.rb
This automatic PR was triggered by the release of Coder v2.8.0
> coder 2.8.0

- Formula/coder.rb
This automatic PR was triggered by the release of Coder v2.8.1
> coder 2.8.1

- Formula/coder.rb
This automatic PR was triggered by the release of Coder v2.8.2
> coder 2.8.2

- Formula/coder.rb
This automatic PR was triggered by the release of Coder v2.8.3
> coder 2.8.3

- Formula/coder@1.rb
Verified checksums against https://github.com/coder/coder-v1-cli/releases/tag/v1.44.4
> chore(Formula/coder@1.rb): update to 1.44.4

- Formula/coder.rb
This automatic PR was triggered by the release of Coder v2.8.4
> coder 2.8.4

- Formula/coder.rb
This automatic PR was triggered by the release of Coder v2.8.5
> coder 2.8.5

- Formula/coder.rb
This automatic PR was triggered by the release of Coder v2.9.0
> coder 2.9.0

- Formula/coder.rb
This automatic PR was triggered by the release of Coder v2.10.1
> coder 2.10.1

- Formula/coder.rb
This automatic PR was triggered by the release of Coder v2.10.2
> coder 2.10.2

- Formula/coder.rb
This automatic PR was triggered by the release of Coder v2.11.0
> coder 2.11.0

- Formula/coder.rb
This automatic PR was triggered by the release of Coder v2.11.1
> coder 2.11.1

- Formula/coder.rb
This automatic PR was triggered by the release of Coder v2.11.2
> coder 2.11.2

- Formula/coder.rb
This automatic PR was triggered by the release of Coder v2.12.0
> coder 2.12.0

- Formula/coder.rb
This automatic PR was triggered by the release of Coder v2.12.1
> coder 2.12.1

- Formula/coder.rb
This automatic PR was triggered by the release of Coder v2.12.2
> coder 2.12.2

- Formula/coder.rb
This automatic PR was triggered by the release of Coder v2.12.3
> coder 2.12.3

- Formula/coder.rb
This automatic PR was triggered by the release of Coder v2.13.0
> coder 2.13.0

- Formula/coder.rb
This automatic PR was triggered by the release of Coder v2.13.1
> coder 2.13.1

- Formula/coder.rb
This automatic PR was triggered by the release of Coder v2.13.2
> coder 2.13.2

- Formula/coder.rb
This automatic PR was triggered by the release of Coder v2.13.4
> coder 2.13.4

- Formula/coder.rb
This automatic PR was triggered by the release of Coder v2.14.0
> coder 2.14.0

- Formula/coder.rb
This automatic PR was triggered by the release of Coder v2.14.1
> coder 2.14.1

- Formula/coder.rb
This automatic PR was triggered by the release of Coder v2.14.2
> coder 2.14.2

- Formula/coder.rb
This automatic PR was triggered by the release of Coder v2.16.0
> coder 2.16.0

- Formula/coder.rb
This automatic PR was triggered by the release of Coder v2.16.1
> coder 2.16.1

- Formula/coder.rb
This automatic PR was triggered by the release of Coder v2.17.0
> coder 2.17.0

- Formula/coder.rb
This automatic PR was triggered by the release of Coder v2.17.2
> coder 2.17.2

- Formula/coder.rb
This automatic PR was triggered by the release of Coder v2.18.0
> coder 2.18.0

- Formula/coder.rb
This automatic PR was triggered by the release of Coder v2.18.1
> coder 2.18.1

- Formula/coder.rb
This automatic PR was triggered by the release of Coder v2.18.2
> coder 2.18.2

- Formula/coder.rb
This automatic PR was triggered by the release of Coder v2.18.3
> coder 2.18.3

- Formula/coder.rb
This automatic PR was triggered by the release of Coder v2.18.4
> coder 2.18.4

- Formula/coder.rb
This automatic PR was triggered by the release of Coder v2.18.5
> coder 2.18.5

- Formula/coder.rb
This automatic PR was triggered by the release of Coder v2.19.0
> coder 2.19.0

- Casks/coder-desktop-preview.rb
This automatic PR was triggered by the release of Coder Desktop v0.1.0-10-gf33afbd
> Coder Desktop v0.1.0-10-gf33afbd

- Casks/coder-desktop-preview.rb
This automatic PR was triggered by the release of Coder Desktop v0.1.0-11-g3442516
> Coder Desktop v0.1.0-11-g3442516

- Casks/coder-desktop-preview.rb
This automatic PR was triggered by the release of Coder Desktop v0.1.0-12-gf970cfc
> Coder Desktop v0.1.0-12-gf970cfc

- Casks/coder-desktop-preview.rb
This automatic PR was triggered by the release of Coder Desktop v0.1.0-13-g98c184d
> Coder Desktop v0.1.0-13-g98c184d

- Casks/coder-desktop-preview.rb
This automatic PR was triggered by the release of Coder Desktop v0.1.0-15-gea73a0a
> Coder Desktop v0.1.0-15-gea73a0a

- Casks/coder-desktop-preview.rb
This automatic PR was triggered by the release of Coder Desktop v0.1.0-17-g5b4b174
> Coder Desktop v0.1.0-17-g5b4b174

- Casks/coder-desktop-preview.rb
This automatic PR was triggered by the release of Coder Desktop v0.1.0-18-g3a520d5
> Coder Desktop v0.1.0-18-g3a520d5

- Casks/coder-desktop-preview.rb
This automatic PR was triggered by the release of Coder Desktop v0.1.0-19-ga906e98
> Coder Desktop v0.1.0-19-ga906e98

- Casks/coder-desktop-preview.rb
This automatic PR was triggered by the release of Coder Desktop v0.1.0-21-gae51d0e
> Coder Desktop v0.1.0-21-gae51d0e

- Formula/coder.rb
This automatic PR was triggered by the release of Coder v2.20.0
> coder 2.20.0

- Casks/coder-desktop-preview.rb
This automatic PR was triggered by the release of Coder Desktop v0.1.0-22-g2dee620
> Coder Desktop v0.1.0-22-g2dee620

- Casks/coder-desktop-preview.rb
This automatic PR was triggered by the release of Coder Desktop v0.1.0-26-g75f015c
> Coder Desktop v0.1.0-26-g75f015c

- Casks/coder-desktop-preview.rb
This automatic PR was triggered by the release of Coder Desktop v0.1.0-27-ge18f466
> Coder Desktop v0.1.0-27-ge18f466

- Casks/coder-desktop.rb
This automatic PR was triggered by the release of Coder Desktop v0.2.0
> Coder Desktop v0.2.0

- Casks/coder-desktop-preview.rb
This automatic PR was triggered by the release of Coder Desktop v0.2.0-1-gb7ccbca
> Coder Desktop v0.2.0-1-gb7ccbca

- Casks/coder-desktop-preview.rb
This automatic PR was triggered by the release of Coder Desktop v0.2.0-2-g2094e9f
> Coder Desktop v0.2.0-2-g2094e9f

- Casks/coder-desktop-preview.rb
This automatic PR was triggered by the release of Coder Desktop v0.2.0-4-g93e7a8f
> Coder Desktop v0.2.0-4-g93e7a8f

- Casks/coder-desktop-preview.rb
This automatic PR was triggered by the release of Coder Desktop v0.2.0-9-g0550ad1
> Coder Desktop v0.2.0-9-g0550ad1

- Casks/coder-desktop-preview.rb
This automatic PR was triggered by the release of Coder Desktop v0.2.0-11-g2603ace
> Coder Desktop v0.2.0-11-g2603ace

- Formula/coder.rb
This automatic PR was triggered by the release of Coder v2.20.2
> coder 2.20.2

- Casks/coder-desktop-preview.rb
This automatic PR was triggered by the release of Coder Desktop v0.2.0-12-g4fb7970
> Coder Desktop v0.2.0-12-g4fb7970

- Casks/coder-desktop-preview.rb
This automatic PR was triggered by the release of Coder Desktop v0.2.0-15-gd95289b
> Coder Desktop v0.2.0-15-gd95289b

- Casks/coder-desktop-preview.rb
This automatic PR was triggered by the release of Coder Desktop v0.2.0-19-g6463de0
> Coder Desktop v0.2.0-19-g6463de0

- Casks/coder-desktop-preview.rb
This automatic PR was triggered by the release of Coder Desktop v0.2.0-21-g1fd5855
> Coder Desktop v0.2.0-21-g1fd5855

- Formula/coder.rb
This automatic PR was triggered by the release of Coder v2.21.0
> coder 2.21.0

- Casks/coder-desktop-preview.rb
This automatic PR was triggered by the release of Coder Desktop v0.2.0-23-g9f625fd
> Coder Desktop v0.2.0-23-g9f625fd

- Casks/coder-desktop-preview.rb
This automatic PR was triggered by the release of Coder Desktop v0.2.0-25-g8067574
> Coder Desktop v0.2.0-25-g8067574

- Casks/coder-desktop.rb
This automatic PR was triggered by the release of Coder Desktop v0.3.0
> Coder Desktop v0.3.0

- Casks/coder-desktop-preview.rb
This automatic PR was triggered by the release of Coder Desktop v0.3.0-1-g918bacd
> Coder Desktop v0.3.0-1-g918bacd

- Casks/coder-desktop-preview.rb
This automatic PR was triggered by the release of Coder Desktop v0.3.0-2-gafd9634
> Coder Desktop v0.3.0-2-gafd9634

- Casks/coder-desktop-preview.rb
This automatic PR was triggered by the release of Coder Desktop v0.3.0-3-g33da515
> Coder Desktop v0.3.0-3-g33da515

- Casks/coder-desktop-preview.rb
This automatic PR was triggered by the release of Coder Desktop v0.3.0-4-g681a9a6
> Coder Desktop v0.3.0-4-g681a9a6

- Formula/coder.rb
This automatic PR was triggered by the release of Coder v2.21.3
> coder 2.21.3

- Casks/coder-desktop-preview.rb
This automatic PR was triggered by the release of Coder Desktop v0.3.0-8-g6417d16
> Coder Desktop v0.3.0-8-g6417d16

- Casks/coder-desktop-preview.rb
This automatic PR was triggered by the release of Coder Desktop v0.3.0-9-g79b0f7c
> Coder Desktop v0.3.0-9-g79b0f7c

- Casks/coder-desktop-preview.rb
This automatic PR was triggered by the release of Coder Desktop v0.3.0-12-g565665f
> Coder Desktop v0.3.0-12-g565665f

- Casks/coder-desktop-preview.rb
This automatic PR was triggered by the release of Coder Desktop v0.3.0-13-g49fd303
> Coder Desktop v0.3.0-13-g49fd303

- Casks/coder-desktop-preview.rb
This automatic PR was triggered by the release of Coder Desktop v0.3.0-16-g314edbe
> Coder Desktop v0.3.0-16-g314edbe

- Casks/coder-desktop.rb
This automatic PR was triggered by the release of Coder Desktop v0.4.0
> Coder Desktop v0.4.0

- Casks/coder-desktop-preview.rb
This automatic PR was triggered by the release of Coder Desktop v0.4.0-1-g37d7e35
> Coder Desktop v0.4.0-1-g37d7e35

- Casks/coder-desktop-preview.rb
This automatic PR was triggered by the release of Coder Desktop v0.4.0-2-g05e41b7
> Coder Desktop v0.4.0-2-g05e41b7

- Casks/coder-desktop-preview.rb
This automatic PR was triggered by the release of Coder Desktop v0.4.0-3-g9f356e5
> Coder Desktop v0.4.0-3-g9f356e5

- Casks/coder-desktop.rb
This automatic PR was triggered by the release of Coder Desktop v0.4.1
> Coder Desktop v0.4.1

- Formula/coder.rb
This automatic PR was triggered by the release of Coder v2.22.1
> coder 2.22.1

- Casks/coder-desktop-preview.rb
This automatic PR was triggered by the release of Coder Desktop v0.4.1-3-g117d8fd
> Coder Desktop v0.4.1-3-g117d8fd

- Casks/coder-desktop-preview.rb
This automatic PR was triggered by the release of Coder Desktop v0.4.1-4-g29c4f41
> Coder Desktop v0.4.1-4-g29c4f41

- Casks/coder-desktop.rb
This automatic PR was triggered by the release of Coder Desktop v0.5.0
> Coder Desktop v0.5.0

- Casks/coder-desktop-preview.rb
This automatic PR was triggered by the release of Coder Desktop v0.5.0-1-gb2da490
> Coder Desktop v0.5.0-1-gb2da490

- Casks/coder-desktop.rb
This automatic PR was triggered by the release of Coder Desktop v0.6.0
> Coder Desktop v0.6.0

- Formula/coder.rb
This automatic PR was triggered by the release of Coder v2.23.0
> coder 2.23.0

- Casks/coder-desktop.rb
This automatic PR was triggered by the release of Coder Desktop v0.7.0
> Coder Desktop v0.7.0

- Casks/coder-desktop.rb
This automatic PR was triggered by the release of Coder Desktop v0.7.1
> Coder Desktop v0.7.1

- Formula/coder.rb
This automatic PR was triggered by the release of Coder v2.24.2
> coder 2.24.2

- Formula/coder.rb
This automatic PR was triggered by the release of Coder v2.25.1
> coder 2.25.1

- Casks/coder-desktop.rb
This automatic PR was triggered by the release of Coder Desktop v0.8.0
> Coder Desktop v0.8.0

- Formula/coder.rb
This automatic PR was triggered by the release of Coder v2.26.0
> coder 2.26.0

- Formula/coder.rb
This automatic PR was triggered by the release of Coder v2.27.0
> coder 2.27.0
